project:
  type: manuscript
  output-dir: "../docs"
execute:
  freeze: auto

format:
  html:
    output-file: "index"
    toc: true
    theme: spacelab
    comments:
      hypothesis: true
  docx: 
    output-file: "Heatwaves_MedSea"
render: 
  - "!*.qmd"
  - "!*.ipynb"
  - "!*.out.ipynb"
resources:
  - "!*.qmd"
  - "!*.ipynb"
  - "!*.out.ipynb"
  - "!*.embed.ipynb"

bibliography: library.bib

files:
  - Manuscript/Data_Processing.qmd